apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  host: <rds-endpoint>     # Example: my-postgres-db.abc123xyz.us-east-1.rds.amazonaws.com
  user: admin
  pass: admin1234
