name: CI/CD Pipeline with Terraform

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: Terraform Infrastructure Deployment
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ${{ github.workspace }}/3tier_app/infrastructure

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          path: 3tier_app  # Ensures all relative paths are resolved correctly

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5  # Recommend using latest stable, not 1.12.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

  deploy:
    name: Build, Scan, and Deploy
    runs-on: self-hosted
    needs: terraform  # Wait for infrastructure setup
    defaults:
      run:
        working-directory: ${{ github.workspace }}/3tier_app

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          path: 3tier_app

      # ---------- SonarQube Scan ----------
      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=my-project
            -Dsonar.organization=my-org
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # ---------- Install Trivy ----------
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          sudo mv trivy /usr/local/bin/trivy

      # ---------- AWS & ECR ----------
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # ---------- Frontend ----------
      - name: Build and Push Frontend Image
        run: |
          cd frontend
          docker build -t frontend .
          trivy image frontend
          docker tag frontend:latest 958978679682.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
          docker push 958978679682.dkr.ecr.us-east-1.amazonaws.com/frontend:latest

      # ---------- Backend ----------
      - name: Build and Push Backend Image
        run: |
          cd backend
          docker build -t backend .
          trivy image backend
          docker tag backend:latest 958978679682.dkr.ecr.us-east-1.amazonaws.com/backend:latest
          docker push 958978679682.dkr.ecr.us-east-1.amazonaws.com/backend:latest

      # ---------- Deploy to Kubernetes ----------
      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --name my-eks-cluster --region us-east-1

      - name: Apply Kubernetes Manifests
        run: |
          cd manifests
          kubectl apply -f db-secret.yaml
          kubectl apply -f backend.yaml
          kubectl apply -f frontend.yaml
