name: CI/CD Pipeline with Terraform

on:
  push:
    branches: 
      - master

jobs:
  terraform:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4  # Checks out your entire repository

      - name: Verify repository structure
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          echo "Infrastructure directory:"
          ls -la infrastructure  # Adjust if your Terraform directory has a different name

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init
        run: terraform init
        working-directory: infrastructure  # Change this to match your actual directory name

      - name: Terraform Plan
        run: terraform plan
        working-directory: infrastructure

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: infrastructure

  deploy:
    runs-on: self-hosted
    needs: [terraform]  # Ensure deploy runs after terraform
    steps:
      - uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=my-project
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          sudo mv trivy /usr/local/bin/trivy

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Frontend
        run: |
          cd frontend
          docker build -t frontend .
          trivy image --exit-code 0 --severity HIGH,CRITICAL frontend
          docker tag frontend:latest 958978679682.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
          docker push 958978679682.dkr.ecr.us-east-1.amazonaws.com/frontend:latest

      - name: Build and Push Backend
        run: |
          cd backend
          docker build -t backend .
          trivy image --exit-code 0 --severity HIGH,CRITICAL backend
          docker tag backend:latest 958978679682.dkr.ecr.us-east-1.amazonaws.com/backend:latest
          docker push 958978679682.dkr.ecr.us-east-1.amazonaws.com/backend:latest

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name my-eks-cluster --region us-east-1

      - name: Deploy to Kubernetes
        run: |
          cd manifests
          kubectl apply -f db-secret.yaml
          kubectl apply -f backend.yaml
          kubectl apply -f frontend.yaml
