name: CI/CD Pipeline with Terraform

on:
  push:
    branches:
      - master

jobs:
  #####################################
  # Terraform Job
  #####################################
  terraform:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./infrastructure

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify directory structure
        run: |
          echo "Current path: $(pwd)"
          ls -R

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Terraform Output to GitHub Env
        id: tf_output
        run: |
          terraform output -json > tf_output.json
          echo "DB_ENDPOINT=$(jq -r '.db_endpoint.value' tf_output.json)" >> $GITHUB_ENV
          echo "VPC_ID=$(jq -r '.vpc_id.value' tf_output.json)" >> $GITHUB_ENV

  #####################################
  # Deploy Job - depends on terraform
  #####################################
  deploy:
    runs-on: self-hosted
    needs: terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      #####################################
      # SonarQube Scan
      #####################################
      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      #####################################
      # Install Trivy
      #####################################
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          sudo install -m 755 trivy /usr/local/bin/trivy

      #####################################
      # AWS Configuration & ECR Login
      #####################################
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      #####################################
      # Build & Push Frontend
      #####################################
      - name: Build and Push Frontend
        run: |
          docker build -t frontend ./3tier_app/frontend
          trivy image frontend
          docker tag frontend:latest 958978679682.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
          docker push 958978679682.dkr.ecr.us-east-1.amazonaws.com/frontend:latest

      #####################################
      # Build & Push Backend
      #####################################
      - name: Build and Push Backend
        run: |
          docker build -t backend ./3tier_app/backend
          trivy image backend
          docker tag backend:latest 958978679682.dkr.ecr.us-east-1.amazonaws.com/backend:latest
          docker push 958978679682.dkr.ecr.us-east-1.amazonaws.com/backend:latest

      #####################################
      # Update kubeconfig & Deploy to EKS
      #####################################
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name my-eks-cluster --region us-east-1

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./3tier_app/manifests/db-secret.yaml
          kubectl apply -f ./3tier_app/manifests/backend.yaml
          kubectl apply -f ./3tier_app/manifests/frontend.yaml

      - name: Print Terraform Outputs
        run: |
          echo "Database Endpoint: $DB_ENDPOINT"
          echo "VPC ID: $VPC_ID"
